### ISSUE TITLE
Bug in dialogue flow

### ISSUE THREAD

**Issue by NoB0** [iai-group/MovieBot#171]
The MovieBot stopped with the following error when trying to get a list of recommendation.

```
Traceback (most recent call last):
  File "/Users/2925364/miniconda3/envs/moviebot/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/2925364/miniconda3/envs/moviebot/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/run.py", line 76, in <module>
    CONTROLLER.execute_agent()
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/controller/controller_terminal.py", line 63, in execute_agent
    ) = agent.continue_dialogue(user_utterance, user_options)
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/agent/agent.py", line 230, in continue_dialogue
    agent_response, options = self.nlg.generate_output(
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/nlg/nlg.py", line 326, in generate_output
    self._user_options_remove_preference(
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/nlg/nlg.py", line 636, in _user_options_remove_preference
    param_key = DialogueAct(UserIntents.REMOVE_PREFERENCE, [param])
  File "/Users/2925364/Documents/VisualCode/moviebot/moviebot/dialogue_manager/dialogue_act.py", line 36, in __init__
    assert all(
AssertionError: All params should be of ItemConstraint type: ['genres']
```

How to reproduce:

```
AGENT: How can I assist you today?
USER:  I want to get a list of movies with war crimes
 AGENT: There are almost 1800 war films. Can you guide me more to narrow down the search space?

Which genres do you prefer? For example, 'War' or 'Sci-Fi'.
USER:  war
```

**Comment by NoB0** [comment]
Fixed in PR #188
